// Design tokens — matches @theme block in globals.css
export const T = {
  bg:         "#F5F3EF",
  surface:    "#FFFFFF",
  surfaceAlt: "#F0EDE8",
  border:     "#DDD8D0",
  borderSoft: "#EBE7E0",
  ink:        "#1A1A2E",
  inkMid:     "#555566",
  inkFaint:   "#9A9AAB",
  cobalt:     "#1B3A5C",
  cobaltL:    "#EFF4F9",
  teal:       "#2E7D6F",
  tealL:      "#EDF5F3",
  gold:       "#C4841D",
  goldL:      "#FDF6EC",
  goldAcc:    "#E09B3D",
  green:      "#1A7A56",
  greenL:     "#EEF7F2",
  greenAcc:   "#2EA06B",
  red:        "#C93535",
  redL:       "#FDF1F1",
  redAcc:     "#E05252",
  fontMono:   "'JetBrains Mono', 'Courier New', monospace",
  fontSans:   "'Inter', system-ui, -apple-system, sans-serif",
};
