// Design tokens — matches @theme block in globals.css
export const T = {
  bg:         "#F8FAFC",
  surface:    "#FFFFFF",
  surfaceAlt: "#F1F5F9",
  border:     "#E2E8F0",
  borderSoft: "#F1F5F9",
  ink:        "#0F172A",
  inkMid:     "#475569",
  inkFaint:   "#94A3B8",
  cobalt:     "#4F46E5",
  cobaltL:    "#EEF2FF",
  teal:       "#0891B2",
  tealL:      "#ECFEFF",
  gold:       "#D97706",
  goldL:      "#FFFBEB",
  goldAcc:    "#F59E0B",
  green:      "#059669",
  greenL:     "#ECFDF5",
  greenAcc:   "#10B981",
  red:        "#DC2626",
  redL:       "#FEF2F2",
  redAcc:     "#EF4444",
  fontMono:   "'JetBrains Mono', 'Courier New', monospace",
  fontSans:   "'Inter', system-ui, -apple-system, sans-serif",
};
