export const personInit = {
  bruto: "", ret: "", redExtra: "",
  tipoContrato: "indefinido", rentasNoLab: "", discapacidad: "ninguna",
  viudedad: false, cuidado: "ninguno", otrasDeducNF3: "",
  viviendaCompra: "", viviendaPerfil: "general",
  alquilerAnual: "", alquilerPerfil: "general",
  edad: "menor65", despoblacion: false, ascendientes: 0,
  ingresosCap_inm: "", gastosCap_inm: "", esViviendaInq: false,
  capMob: "", retCapMob: "",
  gananciasPatr: "",
  retribEspecie: "",
  stockOptions: "",
  stockOptionsReduccion: false,
  rescatePension: "",
  rescatePensionReduccion: false,
  anualidadesAlimentos: "",
  numHijosAlimentos: 1,
  discapFamiliar: 0,
  discapFamiliarGrado: "ninguna",
  asistPersonal: "",
  viviendaPrimerAnio: false,
  donaciones: "",
  donacionesPrioritarias: false,
  inversionNuevaCreacion: "",
};
